services:
  app:
    build:
      target: final

    user: ${USER_ID:-1000}
    ports:
      - "60002:6002"

    volumes:
      - ./db:/wd/db

    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1

    develop:
      watch:
        - action: sync
          path: ./app.py
          target: /wd/app.py
        - action: sync
          path: ./apps/
          target: /wd/apps/

        - action: rebuild
          path: pyproject.toml
        - action: rebuild
          path: uv.lock
        - action: rebuild
          path: .python-version

    # https://docs.docker.com/reference/compose-file/services/#init
    # https://github.com/krallin/tini
    # https://github.com/krallin/tini/issues/8
    init: true

    command: --host 0.0.0.0
